### ISSUE TITLE
Docker image does not work?

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-avatars#28]
```
docker logs 76319baf7fd8
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/app/code/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by j3k0** [comment]
---
fixed the path to `index.js`, next error:

```
docker logs 937c7c3a010b
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/app/code/build/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
